config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'schools#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'log_out'
  delete '/logout', to: 'sessions#destroy'

  # get '/users/new', to: 'users#new', as: 'new_users'
  # post '/users', to: 'users#create'
  # get '/users/:id', to: 'users#show', as: 'user'


  # get '/users/:id/edit', to: 'users#edit', as: 'edit_profile'
  # put '/users/:id', to: 'users#edit'
  # patch '/users/:id', to: 'users#update'
  resources :users


  resources :schools do
    resources :courses do
      post '/favorite', to: 'favorites#create'
      resources :posts
    end
  end

  get '/myactivity/:id', to: 'users#my_activity', as: 'my_activity'

  get '/about', to: 'users#about', as: 'about'
  get '/allschools', to: 'schools#all_schools', as: 'all_schools'


  get '/users/:id/selectschool', to: 'user_schools#new', as: 'select_school'
  post '/users/:id/selectschool', to: 'user_schools#create', as: 'user_schools'
  delete '/users/:id', to: 'user_schools#destroy', as: 'destroy_school_assoc'
  get '/allusers', to: 'users#index', as: 'users_show'

  post '/users/:friend_id/friendships', to: 'friendships#create', as: 'friendships'
  delete '/users/:friend_id/friendships', to: 'friendships#destroy', as: 'destroy_friend'
  patch '/users/:friend_id/friendships', to: 'friendships#accept_friend', as: 'accept_friendship'

  get '/other_user/:id', to: 'users#view_other_user', as: 'other_user'


end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, uniqueness: true
	validates :phone, presence: true
	validates :username, presence: true, uniqueness: true
	validates :tutor, presence: true

	# User has many posts
	has_many :posts, dependent: :destroy
	
	# User has many favorite courses
	has_many :favorites, dependent: :destroy


	# User has many Schools through user_school
	has_many :user_school
	has_many :schools, :through => :user_school

	# User has many Courses through user_course
	has_many :user_course
	has_many :courses, :through => :user_course

	# Users can be friends with other users
	has_many :friendships
	has_many :friends, :through => :friendships
	# determine what other users have added a user as a friend
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

	# determine if a user is a tutor of a course
	has_many :is_tutors

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: ['edit','update','destroy']

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.save
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "You've successfully signed up."
			redirect_to root_path
		else
      flash[:notice] = "Please fill in the fields correctly."
			render 'new'
		end
	end

	def edit
		@user = User.find(session[:user_id]) if session[:user_id]
	end

	def update
		@user = User.find(session[:user_id]) if session[:user_id]
		if @user.update(user_params)
      flash[:notice] = 'User Profile has been updated successfully.'
      redirect_to user_path(@user)
	   else
	   	flash[:notice] = 'Please fill in all fields correctly to update profile.'
	    render :edit
	   end
	end

	def destroy
	end

	# methods for my activity page
	def my_activity
		@user = User.find(session[:user_id]) if session[:user_id]
		@schools = @user.schools
		@courses = Course.all
	end



	private
	def user_params
		params.require(:user).permit(:username, :password, :first_name, :last_name, :email, :phone, :tutor)
	end

end

app/views/users/edit.html.erb
<div class="row">
	<div class="medium-12 columns">
		<h3>Edit Profile</h3>
	</div>
</div>

<div class="row">
	<div class="medium-12 columns">
		<div id='sign-up'>
			<%= form_for(@user, url: { action: 'update' }) do |f| %>
			  <div class="field"><%= f.text_field :first_name, :size => 40, :placeholder => "First Name" %></div>
			  <div class="field"><%= f.text_field :last_name, :size => 40, :placeholder => "Last Name" %></div>
			  <div class="field"><%= f.text_field :email, :size => 40, :placeholder => "Email" %></div>
			  <div class="field"><%= f.text_field :phone, :size => 40, :placeholder => "Phone" %></div>
			  <div class="field"><%= f.text_field :username, :size => 40, :placeholder => "Username" %></div>
			  <div class="field"><%= f.password_field :password, :size => 40, :placeholder => "Password" %></div>
			  <%= f.hidden_field :tutor, value: @user.tutor %>
			  <div class="actions"><%= f.submit 'Update Profile', class: "button medium" %></div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<h5>This is a list of all the students that have signed up to use the website.</h5>

<% @users.each do |user| %>

	<%= gravatar_image_tag(user.email) %>
	<p><%= link_to user.username, other_user_path(user) %></p>

	<% user.schools.limit(1).each do |school| %>
		<p><%= link_to school.name, school_path(school) %></p>
	<% end %>
	
	<p><%= link_to "Follow #{user.username}", friendships_path(:friend_id => user), :method => :post, class: 'button medium' %></p>

<% end %>

app/views/users/my_activity.html.erb
<div class="row">
	<div class="medium-6 columns">
		<h3>My Recent Posts:</h3>

		<% @user.posts.limit(5).each do |post| %>
			<p><strong><%= display_datetime(post.created_at) %></strong></p>
			<p><%= link_to post.school.name, school_path(post.school) %></p>
			<p><%= post.course.name %></p>
			<p><strong><%= link_to post.title, school_course_post_path(post.school_id,post.course_id,post) %></strong></p>
			<p><%= post.description %></p>
		<% end %>

	</div>
	<div class="medium-6 columns">
		<h3>People I'm Following:</h3>

		<% @user.friendships.each do |friendship| %>
			<%= gravatar_image_tag(friendship.friend.email) %>
			
			<p><%= link_to friendship.friend.username, other_user_path(friendship.friend) %></p>
			<p><%= friendship.friend.email %></p>
			<% friendship.friend.schools.limit(1).each do |school| %>
				<p><%= link_to school.name, school_path(school) %></p>
			<% end %>
			<p><%= link_to 'Stop Following', destroy_friend_path(friendship), :method => :delete, class: 'button medium' %></p>

		<% end %>
		<%= link_to 'view all students online here', users_path %>

	</div>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="medium-12 columns">
		<h3>Sign Up</h3>
	</div>
</div>

<div class="row">
	<div class="medium-12 columns">
		<div id='sign-up'>
			<%= form_for(@user, url: { action: 'create' }) do |f| %>
			  <div class="field"><%= f.text_field :first_name, :size => 40, :placeholder => "First Name" %></div>
			  <div class="field"><%= f.text_field :last_name, :size => 40, :placeholder => "Last Name" %></div>
			  <div class="field"><%= f.text_field :email, :size => 40, :placeholder => "Email" %></div>
			  <div class="field"><%= f.text_field :phone, :size => 40, :placeholder => "Phone" %></div>
			  <div class="field"><%= f.text_field :username, :size => 40, :placeholder => "Username" %></div>
			  <div class="field"><%= f.password_field :password, :size => 40, :placeholder => "Password" %></div>
			  <%= f.hidden_field :tutor, value: "false" %>
			  <div class="actions"><%= f.submit 'Sign Up', class: "button medium" %></div>
			<% end %>

			<h5>Already have an account?</h5>
			<%= link_to 'Log in to your account', login_path %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="row ctr">
	<div class="medium-12 columns">
		<h3>My Profile Page</h3>
	</div>
</div>

<div class="row pad2">
	<div class="medium-6 columns">

		<h4>My Profile Info</h4>

		<div class="pad5">
		<%= gravatar_image_tag(@user.email) %>

			<p><strong>First Name:</strong> <%= @user.first_name %></p>
			<p><strong>Last Name:</strong> <%= @user.last_name %></p>
			<p><strong>Email:</strong> <%= @user.email %></p>
			<p><strong>Phone:</strong> <%= @user.phone %></p>
			<p><strong>Username:</strong> <%= @user.username %></p>
		</div>
		<%= link_to 'Edit Profile', edit_user_path(current_user), class: 'button medium' %>

	</div>
	<div class="medium-6 columns">
		<h4>My Favorite Courses</h4>

		<div class="pad5">
			<% @user.favorites.each do |favorite| %>
				<div class="row nomargin pad5">
					<div class="medium-12 columns">
						<% @course = Course.find(favorite.course_id) %>
						<% @school = School.find(@course.school_id) %>
						<p><%= link_to @course.name, school_course_path(@school,@course) %> </p>
					</div>
				</div>
			<% end %>
		</div>

	</div>
</div>

<div class="row pad2">
	<div class="medium-12 columns">
		<h4>My Schools</h4>
	</div>
</div>

<% @user.schools.each do |school| %>
	<div class="row nomargin pad5">
		<div class="medium-12 columns">
			<h5><%= link_to school.name, school_path(school) %> </h5>
		</div>
	</div>
<% end %>

<div class="row nomargin pad75">
	<div class="medium-12 columns">
		<%= link_to "Add a new school to my list", select_school_path(@user), class: 'button medium' %>
	</div>
</div>

	