config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'schools#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'log_out'
  delete '/logout', to: 'sessions#destroy'

  # get '/users/new', to: 'users#new', as: 'new_users'
  # post '/users', to: 'users#create'
  # get '/users/:id', to: 'users#show', as: 'user'


  # get '/users/:id/edit', to: 'users#edit', as: 'edit_profile'
  # put '/users/:id', to: 'users#edit'
  # patch '/users/:id', to: 'users#update'
  resources :users


  resources :schools do
    resources :courses do
      post '/favorite', to: 'favorites#create'
      resources :posts
    end
  end

  get '/myactivity/:id', to: 'users#my_activity', as: 'my_activity'

  get '/about', to: 'users#about', as: 'about'
  get '/allschools', to: 'schools#all_schools', as: 'all_schools'


  get '/users/:id/selectschool', to: 'user_schools#new', as: 'select_school'
  post '/users/:id/selectschool', to: 'user_schools#create', as: 'user_schools'
  delete '/users/:id', to: 'user_schools#destroy', as: 'destroy_school_assoc'
  get '/allusers', to: 'users#index', as: 'users_show'

  post '/users/:friend_id/friendships', to: 'friendships#create', as: 'friendships'
  delete '/users/:friend_id/friendships', to: 'friendships#destroy', as: 'destroy_friend'
  patch '/users/:friend_id/friendships', to: 'friendships#accept_friend', as: 'accept_friendship'

  get '/other_user/:id', to: 'users#view_other_user', as: 'other_user'


end

app/models/school.rb
class School < ApplicationRecord
	# has many Users through user_school
	has_many :user_school
	has_many :users, :through => :user_school

	# has many Courses
	has_many :courses, dependent: :destroy
	has_many :posts, dependent: :destroy

	validates :name, presence: true, uniqueness: true
	validates :location, presence: true
	validates :state, presence: true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

	def index
		@schools = School.all.order("name")
	end

	def show
		@school = School.find(params[:id])
		@courses = @school.courses.all
		@users = @school.users
	end

	def new
		@school = School.new
	end

	def create
		@user = User.find(session[:user_id]) if session[:user_id]
		@school = School.new(school_params)
		if @school.save
			flash[:notice] = "School Successfully created"
			UserSchool.create(user_id: @user.id, school_id: @school.id)
			redirect_to user_path(@user)
		else
			flash[:notice] = "Please fill in the proper fields"
			render 'new'
		end
	end
	
	private

	def school_params
		params.require(:school).permit(:name, :location, :state)
	end
end

app/views/schools/index.html.erb
<div class="row ctr pad2">
	<h3 style="font-weight: bold;">What school are you looking for?</h3>
</div>

<div class="row ctr pad1">
	<%= form_tag schools_path do %>
		<div class="medium-3 columns">&nbsp;</div>
		<div class="medium-5 columns">
			<%= text_field_tag :school_search, '',{class: 'school-search-box', style: 'width:100%;'} %>
		</div>
		<div class="medium-1 columns">
			<%= submit_tag 'Find School', class: 'button medium' %>
		</div>
		<div class="medium-3 columns">&nbsp;</div>
	<% end %>
</div>

<div class="row ctr pad1">
	<h6><%= link_to "Can't find your school? Add it to Course Discuss!", root_path %></h6>
</div>

<div class="row ctr pad2">
	<%= link_to image_tag("illustration.png", class: "", :alt => "logo"), root_path %>
</div>

<% if current_user %>
	<div class="row pad2">
		<div class="medium-12 columns ctr">
			<h4>NEWS FEED</h4>

		</div>
	</div>
	
<% else %>
	<div class="row pad2">
		<div class="medium-12 columns ctr">
			<h5><%= link_to 'Login', login_path %> or <%= link_to 'Sign Up', new_user_path %></h5>
		</div>
	</div>
<% end %>


<div class="row pad2">
	<div class="medium-12 columns ctr">
		<h4>Connect with your classmates and discuss your University courses!</h4>
		<!-- pictures go here, right under text -->
    <div class="row pad2 ctr">
      <div class="medium-3 columns"><%= link_to(image_tag("Michigan_State_Universiy.jpg", :alt => "pic", style: "width:100%; height:260px;"), image_path(root_path, class: "img-responsive")) %>
      </div>
      <div class="medium-3 columns"><%= link_to(image_tag("Alabama-State-University.jpg", :alt => "pic", style: "width:100%; height:260px;"), image_path(root_path, class: "img-responsive")) %>
      </div>
      <div class="medium-3 columns"><%= link_to(image_tag("Indiana-state.jpg", :alt => "pic", style: "width:100%; height:260px;"), image_path(root_path, class: "img-responsive")) %>
      </div>
      <div class="medium-3 columns"><%= link_to(image_tag("columbiacollege.jpg", :alt => "pic", style: "width:100%; height:260px;"), image_path(root_path, class: "img-responsive")) %>
      </div>
    </div>
	</div>
</div>

<div class="row pad2">
	<div class="medium-12 columns ctr">
		<h4>Some of our supported schools:</h4>
		<div class="pad2">
			<% @schools.each do |school| %>
				<p><%= link_to school.name, school_path(school) %></p>
			<% end %>
		</div>
	</div>
</div>



<% if Rails.env.test? == true %>
	<%= link_to 'Log Out', log_out_path, class: 'btn btn-primary'  %>
<% end %>

app/views/schools/new.html.erb
<div class="row">
	<div class="medium-12 columns">
		<h3>Create New School</h3>
	</div>
</div>

<div class="row">
	<div class="medium-12 columns">
		<div id='new-school'>
			<%= form_for @school do |f| %>
			  <p><%= f.text_field :name, :size => 40, :placeholder => "School Name"  %></p>
			  <p><%= f.text_field :location, :size => 40, :placeholder => "City"  %></p>
			  <p><%= f.text_field :state, :size => 40, :placeholder => "State"  %></p>
			  <p><%= f.submit 'Create New School', class: "btn btn-primary" %></p>
			<% end %>
		</div>
	</div>
</div>

app/views/schools/show.html.erb
<div class="row ctr">
	<div class="medium-12 columns">
		<h3><%= @school.name %></h3>
		<h4><%= @school.location %>, <%= @school.state %></h4>
	</div>
</div>

<div class="row pad2">
	<div class="medium-12 columns">
		<h5>Available Courses</h5>
		<% @school.courses.each do |course| %>
			<p><%= link_to course.name, school_course_path(@school,course) %></p>
		<% end %>
	</div>
</div>

<div class="row pad2">
	<div class="medium-12 columns">
		<h5>Students at <%= @school.name %>:</h5>
		<% @users.each do |user| %>
      <p><%= link_to user.username, user_path(user) %></p>
    <% end %>
	</div>
</div>


<div class="row pad2">
	<div class="medium-12 columns">
		<h5>Don't see your course?</h5>
		<% if current_user %>
		  <%= link_to 'Add your course', new_school_course_path(@school,@course), class: 'button medium' %>
		<% else %>
		  <%= link_to 'Add your course', login_path, class: 'button medium' %>
		<% end %>
	</div>
</div>