config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'schools#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'log_out'
  delete '/logout', to: 'sessions#destroy'

  # get '/users/new', to: 'users#new', as: 'new_users'
  # post '/users', to: 'users#create'
  # get '/users/:id', to: 'users#show', as: 'user'


  # get '/users/:id/edit', to: 'users#edit', as: 'edit_profile'
  # put '/users/:id', to: 'users#edit'
  # patch '/users/:id', to: 'users#update'
  resources :users


  resources :schools do
    resources :courses do
      post '/favorite', to: 'favorites#create'
      resources :posts
    end
  end

  get '/myactivity/:id', to: 'users#my_activity', as: 'my_activity'

  get '/about', to: 'users#about', as: 'about'
  get '/allschools', to: 'schools#all_schools', as: 'all_schools'


  get '/users/:id/selectschool', to: 'user_schools#new', as: 'select_school'
  post '/users/:id/selectschool', to: 'user_schools#create', as: 'user_schools'
  delete '/users/:id', to: 'user_schools#destroy', as: 'destroy_school_assoc'
  get '/allusers', to: 'users#index', as: 'users_show'

  post '/users/:friend_id/friendships', to: 'friendships#create', as: 'friendships'
  delete '/users/:friend_id/friendships', to: 'friendships#destroy', as: 'destroy_friend'
  patch '/users/:friend_id/friendships', to: 'friendships#accept_friend', as: 'accept_friendship'

  get '/other_user/:id', to: 'users#view_other_user', as: 'other_user'


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	before_action :set_school

	def index
		@courses = Course.all
	end
	def show
		@course = Course.find(params[:id])
	end
	def new
		@course = Course.new
	end
	def create
		@course = Course.new(course_params)
		if @course.save
      flash[:notice] = 'Course has successfully been created.'
			redirect_to school_path(@school)
		else
      flash[:notice] = 'Please enter all fields correctly.'
			render 'new'
		end
	end
	def edit
		@course = Course.find(params[:id])
	end
	def update
		@course = Course.find(params[:id])
		if @course.update(course_params)
      flash[:notice] = 'Course has successfully been updated.'
			redirect_to school_path(@school)
		else
      flash[:notice] = 'Please enter all fields correctly.'
			render 'edit'
		end
	end
	def destroy
		@course = Course.find(params[:id])
		@course.destroy
    flash[:notice] = 'Course has been successfully deleted.'
		redirect_to school_path(@school)
	end

	private

	def set_school
		@school = School.find(params[:school_id])
	end

	def course_params
		params.require(:course).permit(:name, :description, :school_id)
	end

end

app/views/courses/new.html.erb
<%= form_for(@course, as: :course, url: school_courses_path) do |f| %>
  <p><%= f.text_field :name, :size => 40, :placeholder => "Name"  %></p>

  <p><%= f.text_area :description, size: "60x12", :placeholder => "Description"  %></p>

  <%= f.hidden_field :school_id, :value => params[:school_id] %>

  <p><%= f.submit 'Create a New course', class: "btn btn-primary" %></p>
<% end %>

app/views/courses/show.html.erb
<div class="row ctr">
	<div class="medium-12 columns">
		<h3><%= @course.name %> at <%= @school.name %></h3>
		<h4><%= @course.description %></h4>
	</div>
</div>

<div class="row pad2">
	<div class="medium-12 columns">
		<% if current_user %>
			<% unless Favorite.where(user_id: current_user.id, course_id: @course.id).any? %>
				<%= link_to 'Add Course to Favorites', school_course_favorite_path(@school,@course), method: :post, class: "button medium" %>
			<% end %>
		<% end %>
	</div>
</div>


<!-- allow users to create a post about this course -->
<div class="row pad2">
	<div class="medium-12 columns">
		<h3>Posts about this course:</h3>
	</div>
</div>


<% @course.posts.each do |post| %>
	<div class="row pad25">
		<div class="medium-12 columns">
			<p><%= post.created_at %></p>
			<p><strong><%= post.title %></strong></p>
			<p><%= post.description %></p>
			<p>~ by <%= link_to User.where({id: post.user_id}).first.username, user_path(User.where({id: post.user_id}).first) %></p>
		</div>
	</div>
<% end %>

<div class="row pad2">
	<div class="medium-12 columns">
		<% if current_user %>
			<p><%= link_to "Create New Post", new_school_course_post_path(@school,@course), class: 'button medium' %></p>
		<% else %>
			<p><%= link_to "Create New Post", login_path, class: 'button medium' %></p>
		<% end %>
	</div>
</div>