config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'schools#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'log_out'
  delete '/logout', to: 'sessions#destroy'

  # get '/users/new', to: 'users#new', as: 'new_users'
  # post '/users', to: 'users#create'
  # get '/users/:id', to: 'users#show', as: 'user'


  # get '/users/:id/edit', to: 'users#edit', as: 'edit_profile'
  # put '/users/:id', to: 'users#edit'
  # patch '/users/:id', to: 'users#update'
  resources :users


  resources :schools do
    resources :courses do
      post '/favorite', to: 'favorites#create'
      resources :posts
    end
  end

  get '/myactivity/:id', to: 'users#my_activity', as: 'my_activity'

  get '/about', to: 'users#about', as: 'about'
  get '/allschools', to: 'schools#all_schools', as: 'all_schools'


  get '/users/:id/selectschool', to: 'user_schools#new', as: 'select_school'
  post '/users/:id/selectschool', to: 'user_schools#create', as: 'user_schools'
  delete '/users/:id', to: 'user_schools#destroy', as: 'destroy_school_assoc'
  get '/allusers', to: 'users#index', as: 'users_show'

  post '/users/:friend_id/friendships', to: 'friendships#create', as: 'friendships'
  delete '/users/:friend_id/friendships', to: 'friendships#destroy', as: 'destroy_friend'
  patch '/users/:friend_id/friendships', to: 'friendships#accept_friend', as: 'accept_friendship'

  get '/other_user/:id', to: 'users#view_other_user', as: 'other_user'


end

app/views/layouts/_footer.html.erb
<div class="row pad2 ctr footer">
	<div class="medium-12 columns">
  	<div>Copyright 2017</div>
  </div>
</div>

app/views/layouts/_notice.html.erb
<div class="row pad2 ctr">
	<div class="medium-12 columns">
		<% if flash[:notice] %>
		  <p class="notice" style="color:red;"><%= flash[:notice] %></p>
		<% end %>
	</div>
</div>

app/views/layouts/_topbar.html.erb
<div class="top-bar">
  <div class="row">
    <div class="top-bar-left">
      <%= link_to image_tag("logo.png", class: "logo", :alt => "logo"), root_path %>
    </div>
    <div class="top-bar-right">
      <div class="row">
        <div class="medium-12 columns">
          <% if current_user %>
            <%= link_to 'Home',root_path, class: 'topbar-text-button' %>
            <%= link_to 'My Profile', user_path(current_user), class: 'topbar-text-button' %>
            <%= link_to 'My Activity', my_activity_path(current_user), class: 'topbar-text-button' %>
            <%= link_to 'Log Out',log_out_path, class: 'topbar-text-button' %>
          <% else %>
            <%= link_to 'Home',root_path, class: 'topbar-text-button' %>
            <%= link_to 'Log In',login_path, class: 'topbar-text-button' %>
            <%= link_to 'Sign Up',new_user_path, class: 'topbar-text-button' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/topbar' %>
    <%= render 'layouts/notice' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>